//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Smev3Client.Test
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://mincomsvyaz/esia/reg_service/register_certificate/1.4.2")]
    [System.Xml.Serialization.XmlRootAttribute("ESIARegisterCertificateRequest", Namespace="urn://mincomsvyaz/esia/reg_service/register_certificate/1.4.2", IsNullable=false)]
    public partial class ESIARegisterCertificateRequestType {
        
        private EnvType routingCodeField;
        
        private string serialNumberField;
        
        private string issuerOrgNameField;
        
        private string startDateField;
        
        private string expiryDateField;
        
        private ownertypeType ownerTypeField;
        
        private string snilsField;
        
        private string personINNField;
        
        private string lastNameField;
        
        private string firstNameField;
        
        private string middleNameField;
        
        private genderType genderField;
        
        private bool genderFieldSpecified;
        
        private string birthDateField;
        
        private string birthPlaceField;
        
        private document3Type docField;
        
        private string citizenshipField;
        
        private string ogrnField;
        
        private string orgINNField;
        
        /// <remarks/>
        public EnvType RoutingCode {
            get {
                return this.routingCodeField;
            }
            set {
                this.routingCodeField = value;
            }
        }
        
        /// <remarks/>
        public string serialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
            }
        }
        
        /// <remarks/>
        public string issuerOrgName {
            get {
                return this.issuerOrgNameField;
            }
            set {
                this.issuerOrgNameField = value;
            }
        }
        
        /// <remarks/>
        public string startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        public string expiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
            }
        }
        
        /// <remarks/>
        public ownertypeType ownerType {
            get {
                return this.ownerTypeField;
            }
            set {
                this.ownerTypeField = value;
            }
        }
        
        /// <remarks/>
        public string snils {
            get {
                return this.snilsField;
            }
            set {
                this.snilsField = value;
            }
        }
        
        /// <remarks/>
        public string personINN {
            get {
                return this.personINNField;
            }
            set {
                this.personINNField = value;
            }
        }
        
        /// <remarks/>
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string middleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
            }
        }
        
        /// <remarks/>
        public genderType gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool genderSpecified {
            get {
                return this.genderFieldSpecified;
            }
            set {
                this.genderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string birthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        public string birthPlace {
            get {
                return this.birthPlaceField;
            }
            set {
                this.birthPlaceField = value;
            }
        }
        
        /// <remarks/>
        public document3Type doc {
            get {
                return this.docField;
            }
            set {
                this.docField = value;
            }
        }
        
        /// <remarks/>
        public string citizenship {
            get {
                return this.citizenshipField;
            }
            set {
                this.citizenshipField = value;
            }
        }
        
        /// <remarks/>
        public string ogrn {
            get {
                return this.ogrnField;
            }
            set {
                this.ogrnField = value;
            }
        }
        
        /// <remarks/>
        public string orgINN {
            get {
                return this.orgINNField;
            }
            set {
                this.orgINNField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://mincomsvyaz/esia/commons/rg_sevices_types/1.4.2")]
    public enum EnvType {
        
        /// <remarks/>
        DEV,
        
        /// <remarks/>
        UAT,
        
        /// <remarks/>
        TESIA,
        
        /// <remarks/>
        TCOD,
        
        /// <remarks/>
        PROD,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://mincomsvyaz/esia/commons/rg_sevices_types/1.4.2")]
    public enum ownertypeType {
        
        /// <remarks/>
        PSO,
        
        /// <remarks/>
        ORG,
        
        /// <remarks/>
        IB,
        
        /// <remarks/>
        SYS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://mincomsvyaz/esia/commons/rg_sevices_types/1.4.2")]
    public enum genderType {
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        F,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://mincomsvyaz/esia/commons/rg_sevices_types/1.4.2")]
    public partial class document3Type {
        
        private documenttypeType typeField;
        
        private string seriesField;
        
        private string numberField;
        
        private string issueIdField;
        
        private string issueDateField;
        
        private string expiryDateField;
        
        private string issuedByField;
        
        /// <remarks/>
        public documenttypeType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string series {
            get {
                return this.seriesField;
            }
            set {
                this.seriesField = value;
            }
        }
        
        /// <remarks/>
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public string issueId {
            get {
                return this.issueIdField;
            }
            set {
                this.issueIdField = value;
            }
        }
        
        /// <remarks/>
        public string issueDate {
            get {
                return this.issueDateField;
            }
            set {
                this.issueDateField = value;
            }
        }
        
        /// <remarks/>
        public string expiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
            }
        }
        
        /// <remarks/>
        public string issuedBy {
            get {
                return this.issuedByField;
            }
            set {
                this.issuedByField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://mincomsvyaz/esia/commons/rg_sevices_types/1.4.2")]
    public enum documenttypeType {
        
        /// <remarks/>
        RF_PASSPORT,
        
        /// <remarks/>
        FID_DOC,
        
        /// <remarks/>
        FRGN_PASS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://mincomsvyaz/esia/commons/rg_sevices_types/1.4.2")]
    public partial class errorstatusinfoType {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://mincomsvyaz/esia/reg_service/register_certificate/1.4.2")]
    [System.Xml.Serialization.XmlRootAttribute("ESIARegisterCertificateResponse", Namespace="urn://mincomsvyaz/esia/reg_service/register_certificate/1.4.2", IsNullable=false)]
    public partial class ESIARegisterCertificateResponseType {
        
        private statusType statusField;
        
        private errorstatusinfoType[] errorStatusInfoField;
        
        /// <remarks/>
        public statusType status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("errorStatusInfo")]
        public errorstatusinfoType[] errorStatusInfo {
            get {
                return this.errorStatusInfoField;
            }
            set {
                this.errorStatusInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://mincomsvyaz/esia/commons/rg_sevices_types/1.4.2")]
    public enum statusType {
        
        /// <remarks/>
        VALIDATING,
        
        /// <remarks/>
        VALIDATION_FAILED,
        
        /// <remarks/>
        CONFIRMATION_FAILED,
        
        /// <remarks/>
        SUCCEEDED,
        
        /// <remarks/>
        FAULT,
    }
}
